// ignore_for_file: file_names
// Legacy shim: re-export the correctly named implementation to avoid breaking imports.

// This file is now a re-export of user_model.dart and should not contain any other code.
// features/auth/data/models/user_model.dart
import 'package:json_annotation/json_annotation.dart';

import '../../domain/entities/user.dart';

part 'userModel.g.dart'; // ← generated by build_runner (matches this file name)

@JsonSerializable()
class UserModel {
  final String id;
  final String firstName;
  final String lastName;
  final String email;
  final String? password;
  final String phone;
  final String address;

  const UserModel({
    required this.id,
    required this.firstName,
    required this.lastName,
    required this.email,
    this.password,
    required this.phone,
    required this.address,
  });

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  Map<String, dynamic> toJson() => _$UserModelToJson(this);

  // ==================== MAPPER INSIDE MODEL ====================
  /// Convert this DTO → pure domain entity
  User toDomain() => User(
    id: id,
    firstName: firstName,
    lastName: lastName,
    email: email,
    password: password,
    phone: phone,
    address: address,
  );

  /// Optional: reverse mapping (if you need to go Entity → Model)
  UserModel copyFromEntity(User user) => UserModel(
    id: user.id ?? '',
    firstName: user.firstName ?? '',
    lastName: user.lastName ?? '',
    email: user.email ?? '',
    password: user.password,
    phone: user.phone ?? '',
    address: user.address ?? '',
  );
  // =============================================================

  // ==================== COPYWITH (still useful) =================
  UserModel copyWith({
    String? id,
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? phone,
    String? address,
  }) {
    return UserModel(
      id: id ?? this.id,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      email: email ?? this.email,
      password: password ?? this.password,
      phone: phone ?? this.phone,
      address: address ?? this.address,
    );
  }

  // =============================================================
}

// Inside user_model.dart (bottom)
extension UserEntityX on User {
  UserModel toModel() => UserModel(
    id: id ?? '',
    firstName: firstName ?? '',
    lastName: lastName ?? '',
    email: email ?? '',
    password: password,
    phone: phone ?? '',
    address: address ?? '',
  );
}
