# Generated by Django 5.0.14 on 2025-11-26 12:37
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),

    ]
