# Generated by Django 5.0.14 on 2025-11-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_trigram_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='brand_slug_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='cat_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='cat_slug_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_title_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_slug_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_sku_trgm_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metadata',
        ),
    ]
