# Generated by Django 5.0.14 on 2025-11-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_brand_brand_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE products_product
            DROP CONSTRAINT IF EXISTS products_compare_price_gte_price;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='product',
                    name='products_compare_price_gte_price',
                ),
            ],
        ),
    ]
