# Generated by Django 5.0.14 on 2025-11-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_products_compare_price_gte_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='products_compare_price_gte_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image_url',
        ),
    ]
