# Generated by Django 5.0.14 on 2025-11-27 16:28

from django.db import migrations, models
import uuid

def generate_uuid(apps, schema_editor):
    # We'll fill this in phase 2
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_products_compare_price_gte_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='uuid_id',
            field=models.UUIDField(null=True, blank=True, unique=True),
        ),
    ]
