# Generated by Django 5.0.14 on 2025-11-27 16:28

from django.db import migrations
import uuid

def populate_uuids(apps, schema_editor):
    # For every model that had AutoField -> UUIDField
    for model_name in ['Brand', 'Category', 'Product', 'ProductVariant']:
        Model = apps.get_model('products', model_name)
        for obj in Model.objects.all():
            if not obj.uuid_id:
                obj.uuid_id = uuid.uuid4()
                obj.save(update_fields=['uuid_id'])

    # Now fix all foreign key fields that pointed to old int PK
    # Example: Product.category_id (int) → category.uuid_id
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.category_id:  # old FK
            old_cat = apps.get_model('products', 'Category').objects.get(id=product.category_id)
            product.category = old_cat  # new FK field that points to uuid_id
            product.save(update_fields=['category_id'])

    # Repeat for brand, variants, etc.
    # ProductVariant.product (old int) → new UUID relation
    ProductVariant = apps.get_model('products', 'ProductVariant')
    for variant in ProductVariant.objects.all():
        if variant.product_id:
            old_product = apps.get_model('products', 'Product').objects.get(id=variant.product_id)
            variant.product = old_product
            variant.save(update_fields=['product_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_switch_to_uuid_phase1'),
    ]

    operations = [
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
    ]
