# Generated by Django 5.0.14 on 2025-11-27 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_switch_to_uuid_phase2'),
    ]

    operations = [
        migrations.RemoveField('brand', 'id'),
        migrations.RenameField('brand', 'uuid_id', 'id'),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField('category', 'id'),
        migrations.RenameField('category', 'uuid_id', 'id'),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField('product', 'id'),
        migrations.RenameField('product', 'uuid_id', 'id'),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField('productvariant', 'id'),
        migrations.RenameField('productvariant', 'uuid_id', 'id'),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        
   
    ]
