# Generated by Django 5.0.14 on 2025-11-27 16:47

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_switch_to_uuid_phase2'),
    ]

    operations = [
           migrations.RemoveField(
            model_name='productdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False),
        ),
    ]