# Generated by Django 5.0.14 on 2025-11-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_switch_to_uuid_phase3'),
        ('products', '0010_switch_to_uuid_phase4'),
    ]

    operations = [
    ]
