# Generated by Django 5.0.14 on 2025-11-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_currency_alter_productimage_id'),
        ('products', '0013_switch_to_uuid_phase5'),
    ]

    operations = [
    ]
