import {
  Brand,
  Category,
  Customer,
  Order,
  OrderStatus,
  Product,
  ProductStatus,
  RevenueData,
  SalesData,
  TopSellingProduct,
  User,
  UserRole,
} from "./types";

export const CURRENT_USER: User = {
  id: "u1",
  name: "Kazi Mahbub",
  email: "admin@sadax.studio",
  role: UserRole.SUPER_ADMIN,
  avatarUrl: "https://picsum.photos/100/100?random=user",
  status: "Active",
};

export const REVENUE_DATA: RevenueData[] = [
  { date: "Mon", revenue: 4000, profit: 1200, orders: 24 },
  { date: "Tue", revenue: 3000, profit: 900, orders: 13 },
  { date: "Wed", revenue: 2000, profit: 500, orders: 98 },
  { date: "Thu", revenue: 2780, profit: 890, orders: 39 },
  { date: "Fri", revenue: 1890, profit: 450, orders: 48 },
  { date: "Sat", revenue: 2390, profit: 900, orders: 38 },
  { date: "Sun", revenue: 3490, profit: 1300, orders: 43 },
];

export const CATEGORY_DATA: SalesData[] = [
  { name: "Electronics", value: 400 },
  { name: "Fashion", value: 300 },
  { name: "Home", value: 300 },
  { name: "Beauty", value: 200 },
];

export const MOCK_BRANDS: Brand[] = [
  {
    id: "b1",
    name: "Apple",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    productsCount: 45,
    status: "Active",
    description: "Premium technology products",
  },
  {
    id: "b2",
    name: "Nike",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",
    productsCount: 120,
    status: "Active",
    description: "Athletic footwear and apparel",
  },
  {
    id: "b3",
    name: "Samsung",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg",
    productsCount: 89,
    status: "Active",
    description: "Consumer electronics",
  },
  {
    id: "b4",
    name: "Loreal",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/L%27Or%C3%A9al_logo.svg",
    productsCount: 67,
    status: "Active",
    description: "Beauty and cosmetics",
  },
  {
    id: "b5",
    name: "Sony",
    logoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg",
    productsCount: 34,
    status: "Inactive",
    description: "Audio and visual equipment",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "#1766703570",
    name: "Airpods Pro Max 2024",
    sku: "AP-2024",
    category: "Electronics",
    price: 549.0,
    costPrice: 350.0,
    stock: 45,
    status: ProductStatus.ACTIVE,
    imageUrl: "https://picsum.photos/200/200?random=1",
    sales: 120,
    avgDailySales: 2.5,
    lastSaleDate: "2024-03-10",
    images: [],
  },
  {
    id: "#1766707087",
    name: "Neaithy Beauty Cream",
    sku: "BC-001",
    category: "Beauty",
    price: 55.0,
    costPrice: 20.0,
    stock: 12,
    status: ProductStatus.ACTIVE,
    imageUrl: "https://picsum.photos/200/200?random=2",
    sales: 540,
    avgDailySales: 5.0,
    lastSaleDate: "2024-03-12",
    images: [],
  },
  {
    id: "#1766701234",
    name: "Apple Watch Series 4 New",
    sku: "AW-S4",
    category: "Electronics",
    price: 299.0,
    costPrice: 180.0,
    stock: 0,
    status: ProductStatus.DRAFT,
    imageUrl: "https://picsum.photos/200/200?random=3",
    sales: 32,
    avgDailySales: 0.5,
    lastSaleDate: "2024-01-15",
    images: [],
  },
  {
    id: "#1766727267",
    name: "iPhone 16 Pro Max Plus",
    sku: "IP-16",
    category: "Electronics",
    price: 1099.0,
    costPrice: 800.0,
    stock: 5,
    status: ProductStatus.ACTIVE,
    imageUrl: "https://picsum.photos/200/200?random=4",
    sales: 890,
    avgDailySales: 8.0,
    lastSaleDate: "2024-03-12",
    images: [],
  },
  {
    id: "#1766712323",
    name: "Small Hi-Speed Fan",
    sku: "HF-01",
    category: "Home",
    price: 25.0,
    costPrice: 10.0,
    stock: 0,
    status: ProductStatus.ARCHIVED,
    imageUrl: "https://picsum.photos/200/200?random=5",
    sales: 45,
    avgDailySales: 0,
    lastSaleDate: "2023-12-01",
    images: [],
  },
  {
    id: "#1766712398",
    name: "MI Watch Pro X231 Max",
    sku: "MI-W",
    category: "Electronics",
    price: 150.0,
    costPrice: 90.0,
    stock: 230,
    status: ProductStatus.ACTIVE,
    imageUrl: "https://picsum.photos/200/200?random=6",
    sales: 210,
    avgDailySales: 3.2,
    lastSaleDate: "2024-03-11",
    images: [],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "#01766703570",
    customerName: "Muhammad Fateh",
    customerEmail: "pro@customer.com",
    customerAvatar: "https://picsum.photos/50/50?random=1",
    date: "Jan 01, 2024",
    total: 10120.0,
    status: OrderStatus.ACCEPTED,
    paymentMethod: "Mastercard",
    items: 3,
  },
  {
    id: "#01766707087",
    customerName: "Kazi Mukarram",
    customerEmail: "new@customer.com",
    customerAvatar: "https://picsum.photos/50/50?random=2",
    date: "Feb 24, 2024",
    total: 5180.0,
    status: OrderStatus.ACCEPTED,
    paymentMethod: "Cash on Delivery",
    items: 1,
  },
  {
    id: "#01766701234",
    customerName: "Anderson Mark",
    customerEmail: "star@customer.com",
    customerAvatar: "https://picsum.photos/50/50?random=3",
    date: "Mar 05, 2024",
    total: 13145.0,
    status: OrderStatus.PENDING,
    paymentMethod: "Visa",
    items: 2,
  },
  {
    id: "#01766727267",
    customerName: "John Kales",
    customerEmail: "pro@customer.com",
    customerAvatar: "https://picsum.photos/50/50?random=4",
    date: "Mar 01, 2024",
    total: 50760.0,
    status: OrderStatus.COMPLETED,
    paymentMethod: "Mastercard",
    items: 5,
  },
  {
    id: "#01766712323",
    customerName: "Saleh Ahmed",
    customerEmail: "pro@customer.com",
    customerAvatar: "https://picsum.photos/50/50?random=5",
    date: "Apr 01, 2024",
    total: 10120.0,
    status: OrderStatus.REJECTED,
    paymentMethod: "Mastercard",
    items: 1,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Electronics",
    productsCount: 1200,
    children: [
      {
        id: "1-1",
        name: "Laptops",
        productsCount: 400,
        children: [],
        parentId: "1",
      },
      {
        id: "1-2",
        name: "Smartphones",
        productsCount: 600,
        children: [],
        parentId: "1",
      },
      {
        id: "1-3",
        name: "Cameras",
        productsCount: 200,
        children: [],
        parentId: "1",
      },
    ],
    parentId: null,
  },
  {
    id: "2",
    name: "Fashion",
    productsCount: 3500,
    children: [
      {
        id: "2-1",
        name: "Men",
        productsCount: 1500,
        children: [],
        parentId: "2",
      },
      {
        id: "2-2",
        name: "Women",
        productsCount: 2000,
        children: [],
        parentId: "2",
      },
    ],
    parentId: null,
  },
  {
    id: "3",
    name: "Home & Living",
    productsCount: 800,
    children: [],
    parentId: null,
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "Muhammad Fateh",
    email: "pro@customer.com",
    phone: "+123 456 7890",
    avatarUrl: "https://picsum.photos/50/50?random=1",
    totalOrders: 145,
    totalSpent: 10120.0,
    status: "Active",
    joinDate: "Jan 12, 2023",
  },
  {
    id: "c2",
    name: "Kazi Mukarram",
    email: "new@customer.com",
    phone: "+198 765 4321",
    avatarUrl: "https://picsum.photos/50/50?random=2",
    totalOrders: 23,
    totalSpent: 5180.0,
    status: "Active",
    joinDate: "Feb 28, 2023",
  },
  {
    id: "c3",
    name: "Anderson Mark",
    email: "star@customer.com",
    phone: "+112 233 4455",
    avatarUrl: "https://picsum.photos/50/50?random=3",
    totalOrders: 56,
    totalSpent: 13145.0,
    status: "Blocked",
    joinDate: "Mar 15, 2023",
  },
  {
    id: "c4",
    name: "John Kales",
    email: "john@customer.com",
    phone: "+155 667 7889",
    avatarUrl: "https://picsum.photos/50/50?random=4",
    totalOrders: 89,
    totalSpent: 50760.0,
    status: "Active",
    joinDate: "Apr 02, 2023",
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Kazi Mahbub",
    email: "admin@sadax.studio",
    role: UserRole.SUPER_ADMIN,
    avatarUrl: "https://picsum.photos/50/50?random=user",
    status: "Active",
    lastActive: "Just now",
  },
  {
    id: "u2",
    name: "Sarah Wilson",
    email: "sarah@sadax.studio",
    role: UserRole.STAFF,
    avatarUrl: "https://picsum.photos/50/50?random=u2",
    status: "Active",
    lastActive: "2 hours ago",
  },
  {
    id: "u3",
    name: "David Lee",
    email: "david@sadax.studio",
    role: UserRole.STAFF,
    avatarUrl: "https://picsum.photos/50/50?random=u3",
    status: "Inactive",
    lastActive: "2 days ago",
  },
];

export const MOCK_TOP_PRODUCTS: TopSellingProduct[] = [
  {
    id: "1",
    name: "iPhone 16 Pro Max",
    sku: "IP-16",
    quantitySold: 450,
    revenue: 494550,
    percentage: 24,
  },
  {
    id: "2",
    name: "Airpods Pro Max",
    sku: "AP-24",
    quantitySold: 320,
    revenue: 175680,
    percentage: 18,
  },
  {
    id: "3",
    name: "Samsung Galaxy S24",
    sku: "SG-24",
    quantitySold: 210,
    revenue: 168000,
    percentage: 15,
  },
  {
    id: "4",
    name: "Nike Air Jordan",
    sku: "NK-AJ",
    quantitySold: 180,
    revenue: 45000,
    percentage: 12,
  },
  {
    id: "5",
    name: "Sony WH-1000XM5",
    sku: "SN-XM",
    quantitySold: 150,
    revenue: 52500,
    percentage: 8,
  },
  {
    id: "6",
    name: "MacBook Air M3",
    sku: "MB-A3",
    quantitySold: 90,
    revenue: 108000,
    percentage: 7,
  },
  {
    id: "7",
    name: "Logitech MX Master",
    sku: "LG-MX",
    quantitySold: 85,
    revenue: 8500,
    percentage: 5,
  },
  {
    id: "8",
    name: "Kindle Paperwhite",
    sku: "AM-KP",
    quantitySold: 70,
    revenue: 10500,
    percentage: 4,
  },
  {
    id: "9",
    name: "PlayStation 5",
    sku: "SY-PS",
    quantitySold: 65,
    revenue: 32500,
    percentage: 4,
  },
  {
    id: "10",
    name: "Dyson Airwrap",
    sku: "DY-AW",
    quantitySold: 40,
    revenue: 24000,
    percentage: 3,
  },
];
